# Generated by Django 5.2.14 on 2026-05-08 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (emoji ou classe CSS)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'examen")),
                ('instructions', models.TextField(verbose_name='Instructions & règles')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Durée (minutes)')),
                ('passing_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Score minimum (%)')),
                ('max_attempts_per_week', models.PositiveIntegerField(default=1, verbose_name='Tentatives par semaine')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Examen de Certification',
                'verbose_name_plural': 'Examens de Certification',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre dans le cours')),
            ],
            options={
                'verbose_name': 'Module du Cours',
                'verbose_name_plural': 'Modules du Cours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Prérequis de Cours',
                'verbose_name_plural': 'Prérequis de Cours',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du Parcours')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('short_description', models.CharField(max_length=400, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('professional', 'Professionnel')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='paths/thumbnails/', verbose_name='Image de couverture')),
                ('estimated_weeks', models.PositiveIntegerField(default=12, verbose_name='Durée estimée (semaines)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_certifying', models.BooleanField(default=True, verbose_name='Parcours certifiant')),
                ('is_free', models.BooleanField(default=False, verbose_name='Accès libre')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text="0 = gratuit. L'instructeur décide.", max_digits=10, verbose_name='Prix (FCFA)')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscrits")),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne')),
                ('courses_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre dans le parcours')),
                ('is_required', models.BooleanField(default=True, help_text='Si False, le cours est optionnel pour la certification.', verbose_name='Obligatoire')),
            ],
            options={
                'verbose_name': 'Cours du Parcours',
                'verbose_name_plural': 'Cours du Parcours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('lesson_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte / Lecture'), ('notebook', 'Notebook Interactif'), ('quiz', 'Quiz'), ('exercise', 'Exercice de code')], default='video', max_length=20, verbose_name='Type de leçon')),
                ('content', models.TextField(blank=True, verbose_name='Contenu (Markdown)')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de la vidéo (Mux)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Aperçu gratuit')),
                ('starter_code', models.TextField(blank=True, verbose_name='Code de démarrage')),
                ('solution_code', models.TextField(blank=True, verbose_name='Solution (instructeur)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Durée estimée (heures)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules (Bibliothèque)',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('instructions', models.TextField(verbose_name='Instructions détaillées')),
                ('starter_code', models.TextField(blank=True, verbose_name='Code de démarrage')),
                ('solution_code', models.TextField(blank=True, verbose_name='Solution (instructeur)')),
                ('is_final', models.BooleanField(default=False, verbose_name='Projet de fin de cours (Certifiant)')),
                ('is_capstone', models.BooleanField(default=False, help_text='Si True, la validation de ce projet peut déclencher la certification.', verbose_name='Capstone (Projet certifiant du parcours)')),
                ('passing_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Score minimum pour validation (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Durée estimée (heures)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Image de couverture')),
                ('preview_url', models.URLField(blank=True, verbose_name="URL d'aperçu gratuit (vidéo)")),
                ('prerequisites_text', models.TextField(blank=True, help_text='Description textuelle. La logique métier utilise CoursePrerequisite.', verbose_name='Prérequis (texte affiché)')),
                ('syllabus', models.TextField(blank=True, verbose_name='Syllabus')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_free', models.BooleanField(default=False, verbose_name='Cours gratuit')),
                ('is_standalone', models.BooleanField(default=False, help_text="True = accessible en dehors d'un parcours.", verbose_name='Cours autonome')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix standalone (FCFA)')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscrits")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
    ]
