# Generated by Django 5.2.13 on 2026-05-01 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (emoji ou classe CSS)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Durée estimée (heures)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Image de couverture')),
                ('preview_url', models.URLField(blank=True, verbose_name="URL d'aperçu gratuit (vidéo)")),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('syllabus', models.TextField(blank=True, verbose_name='Syllabus (plan du cours)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_free', models.BooleanField(default=False, verbose_name='Cours gratuit')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscrits")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Catégorie')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Parcours')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('lesson_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte / Lecture'), ('notebook', 'Notebook Interactif'), ('quiz', 'Quiz'), ('exercise', 'Exercice de code')], default='video', max_length=20, verbose_name='Type de leçon')),
                ('content', models.TextField(blank=True, verbose_name='Contenu (Markdown)')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de la vidéo (Mux)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Aperçu gratuit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('instructions', models.TextField(verbose_name='Instructions détaillées')),
                ('starter_code', models.TextField(blank=True, verbose_name='Code de démarrage')),
                ('solution_code', models.TextField(blank=True, verbose_name='Solution (instructeur)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Parcours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
