# Generated by Django 5.2.14 on 2026-05-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_set', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='required_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='courses.course', verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='courses.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur / Instructeur principal'),
        ),
        migrations.AddField(
            model_name='certificationexam',
            name='learning_path',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_exam', to='courses.learningpath', verbose_name='Parcours'),
        ),
        migrations.AddField(
            model_name='learningpathcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_paths', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='learningpathcourse',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='courses.learningpath', verbose_name='Parcours'),
        ),
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_authored', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie thématique pour faciliter la recherche dans la bibliothèque.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='project',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='courses.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='certificationexam',
            name='capstone_project',
            field=models.ForeignKey(blank=True, help_text='Si défini, la validation de ce projet vaut aussi certification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_exam', to='courses.project', verbose_name="Projet Capstone (alternatif à l'examen)"),
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together={('course', 'required_course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='learningpathcourse',
            unique_together={('learning_path', 'course'), ('learning_path', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'module'), ('course', 'order')},
        ),
    ]
