# Generated by Django 5.2.13 on 2026-05-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Projet de fin de cours (Certifiant)'),
        ),
    ]
