# Generated by Django 5.2.14 on 2026-05-22 23:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['title'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courseprerequisite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificationexam',
            name='capstone_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_exam', to='courses.project', verbose_name="Projet Capstone (alternatif à l'examen)"),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_standalone',
            field=models.BooleanField(default=False, verbose_name='Cours autonome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites_text',
            field=models.TextField(blank=True, verbose_name='Prérequis (texte affiché)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie thématique pour faciliter la recherche.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='passing_score',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Score minimum pour validation (%)'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'module'), name='unique_course_module_link'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_course_module_position'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.UniqueConstraint(fields=('course', 'required_course'), name='unique_course_prerequisite_link'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_user_review_link'),
        ),
        migrations.AddConstraint(
            model_name='learningpathcourse',
            constraint=models.UniqueConstraint(fields=('learning_path', 'course'), name='unique_path_course'),
        ),
        migrations.AddConstraint(
            model_name='learningpathcourse',
            constraint=models.UniqueConstraint(fields=('learning_path', 'order'), name='unique_path_order_position'),
        ),
    ]
