# Generated by Django 5.2.13 on 2026-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_project_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='solution_code',
            field=models.TextField(blank=True, verbose_name='Solution (instructeur)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='starter_code',
            field=models.TextField(blank=True, verbose_name='Code de démarrage'),
        ),
    ]
