# Generated by Django 5.2.17 on 2026-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='required_review_count',
            field=models.PositiveIntegerField(default=2, help_text="Nombre d'évaluations nécessaires avant la décision finale (pair review ou instructeur).", verbose_name='Nombre de correcteurs requis'),
        ),
    ]
