# Generated by Django 5.2.13 on 2026-05-08 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_solution_code_lesson_starter_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='is_standalone',
            field=models.BooleanField(default=False, help_text="True = accessible en dehors d'un parcours.", verbose_name='Cours autonome'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites_text',
            field=models.TextField(blank=True, help_text="Description textuelle des prérequis pour l'affichage. La logique métier utilise CoursePrerequisite.", verbose_name='Prérequis (texte affiché)'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix si le cours est acheté individuellement.', max_digits=10, verbose_name='Prix standalone (FCFA)'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Cours'),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre du Parcours')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('short_description', models.CharField(max_length=400, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('professional', 'Professionnel')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='paths/thumbnails/', verbose_name='Image de couverture')),
                ('estimated_weeks', models.PositiveIntegerField(default=12, verbose_name='Durée estimée (semaines)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_certifying', models.BooleanField(default=True, verbose_name='Parcours certifiant')),
                ('is_free', models.BooleanField(default=False, verbose_name='Accès libre')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text="0 = gratuit. L'instructeur décide.", max_digits=10, verbose_name='Prix (FCFA)')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscrits")),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne')),
                ('courses_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='courses.category', verbose_name='Catégorie')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur / Instructeur principal')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'examen")),
                ('instructions', models.TextField(verbose_name='Instructions & règles')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Durée (minutes)')),
                ('passing_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Score minimum (%)')),
                ('max_attempts_per_week', models.PositiveIntegerField(default=1, verbose_name='Tentatives par semaine')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_exam', to='courses.learningpath', verbose_name='Parcours')),
            ],
            options={
                'verbose_name': 'Examen de Certification',
                'verbose_name_plural': 'Examens de Certification',
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_set', to='courses.course', verbose_name='Cours')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_for', to='courses.course', verbose_name='Prérequis')),
            ],
            options={
                'verbose_name': 'Prérequis de Cours',
                'verbose_name_plural': 'Prérequis de Cours',
                'unique_together': {('course', 'required_course')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre dans le parcours')),
                ('is_required', models.BooleanField(default=True, help_text='Si False, le cours est optionnel pour la certification.', verbose_name='Obligatoire')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_paths', to='courses.course', verbose_name='Cours')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='courses.learningpath', verbose_name='Parcours')),
            ],
            options={
                'verbose_name': 'Cours du Parcours',
                'verbose_name_plural': 'Cours du Parcours',
                'ordering': ['order'],
                'unique_together': {('learning_path', 'course'), ('learning_path', 'order')},
            },
        ),
    ]
