# Generated by Django 5.2.14 on 2026-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_options_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Obsolète'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.TextField(blank=True, verbose_name="Objectifs d'apprentissage"),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('review', 'En revue'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Obsolète'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Obsolète'),
        ),
        migrations.AddField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='project',
            name='rubric_content',
            field=models.TextField(blank=True, verbose_name="Grille d'évaluation (Rubrique)"),
        ),
    ]
