# Generated by Django 5.2.14 on 2026-05-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_deprecated_course_learning_objectives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la grille')),
                ('criteria_definition', models.JSONField(default=dict, help_text='Ex: {"clarté": {"max_points": 3}, "technique": {"max_points": 2}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Grille d'évaluation",
                'verbose_name_plural': "Grilles d'évaluation",
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='rubric_content',
        ),
        migrations.AddField(
            model_name='project',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='courses.rubric', verbose_name="Grille d'évaluation"),
        ),
    ]
