# Generated by Django 5.2.14 on 2026-05-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rubric_remove_project_rubric_content_project_rubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_deprecated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_objectives',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='version',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_deprecated',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='version',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_deprecated',
        ),
        migrations.RemoveField(
            model_name='module',
            name='version',
        ),
        migrations.AddField(
            model_name='project',
            name='required_review_count',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de revues nécessaires pour finaliser'),
        ),
    ]
