apiVersion: v1
kind: Secret
metadata:
  name: mlbackend-secrets
  labels:
    app: mlbackend
type: Opaque
# En utilisant stringData, Kubernetes se charge de convertir en Base64 automatiquement
stringData:
  DATABASE_URL: "postgresql://postgres.sspacdgyeuhlvtpsqfef:AY6g%40%2Bns44sS%2FQb@aws-1-eu-central-1.pooler.supabase.com:6543/postgres"
  PASSWORD_DB: "AY6g@+ns44sS/Qb"
  API_AFRI_KEY: "sk-afri-95e3617529aa47bd93cb722f415439e9"
  GITHUB_CLIENT_ID: "Ov23liyDwwgSRcQZ6vys"
  GITHUB_CLIENT_SECRET: "0786d68632570be2d805708cf50f1f611a8f7a90"
  GOOGLE_CLIENT_ID: "906737257830-4hsmklml8ujnqg8ns245c23m9ak98d3c.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  EMAIL_HOST_PASSWORD: "idiqrxluixgmhwwm"
