apiVersion: v1
kind: Secret
metadata:
  name: mlbackend-secrets
  labels:
    app: mlbackend
type: Opaque
# En utilisant stringData, Kubernetes se charge de convertir en Base64 automatiquement
stringData:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLnNzcGFjZGd5ZXVobHZ0cHNxZmVmOkFZNmclNDAlMkJuczQ0c1MlMkZRYkBhd3MtMS1ldS1jZW50cmFsLTEucG9vbGVyLnN1cGFiYXNlLmNvbTo2NTQzL3Bvc3RncmVzCg==
  PASSWORD_DB: QVk2Z0ArbnM0NHNTL1FiCg==
  API_AFRI_KEY: c2stYWZyaS05NWUzNjE3NTI5YWE0N2JkOTNjYjcyMmY0MTU0MzllOQo=
  GITHUB_CLIENT_ID: T3YyM2xpeUR3d2dTUmNRWjZ2eXMK
  GITHUB_CLIENT_SECRET: MDc4NmQ2ODYzMjU3MGJlMmQ4MDU3MDhjZjUwZjFmNjExYThmN2E5MAo=
  GOOGLE_CLIENT_ID: OTA2NzM3MjU3ODMwLTRoc21rbG1sOHVqbnFnOG5zMjQ1YzIzbTlhazk4ZDNjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==

  GOOGLE_CLIENT_SECRET: R09DU1BYLVJOaVVWVW9fbUxQSVRyRzNsNnB6RWhCV05KOUcK
  EMAIL_HOST_PASSWORD: aWRpcXJ4bHVpeGdtaHd3bQo=
