apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  DATABASE_URL: <url_database>
  PASSWORD_DB: <PASSWORD_DB>
  API_AFRI_KEY: <API_AFRI_KEY>
  GITHUB_CLIENT_ID: <GITHUB_CLIENT_ID>
  GITHUB_CLIENT_SECRET: <GITHUB_CLIENT_SECRET>
  GOOGLE_CLIENT_ID: <GOOGLE_CLIENT_ID>
  GOOGLE_CLIENT_SECRET: <GOOGLE_CLIENT_SECRET>
  EMAIL_HOST_PASSWORD: <EMAIL_HOST_PASSWORD>