services:
  - type: web
    name: MLBackend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd MLBackend && daphne -b 0.0.0.0 -p $PORT MLBackend.asgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: mlacademy-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

  - type: redis
    name: mlacademy-redis
    plan: free
    ipAllowList: []
