# Generated by Django 5.2.14 on 2026-05-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Score obtenu (%)')),
                ('passed', models.BooleanField(verbose_name='Réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Tentative d'Examen",
                'verbose_name_plural': "Tentatives d'Examen",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Progression (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Cours terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
            ],
            options={
                'verbose_name': 'Inscription Cours',
                'verbose_name_plural': 'Inscriptions Cours',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Progression (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Parcours terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Certifié')),
            ],
            options={
                'verbose_name': 'Inscription Parcours',
                'verbose_name_plural': 'Inscriptions Parcours',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Note (sur 100)')),
                ('feedback', models.TextField(verbose_name='Commentaires constructifs')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Projet validé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Correction par les pairs',
                'verbose_name_plural': 'Corrections par les pairs',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, verbose_name='URL du dépôt (ex: GitHub)')),
                ('code_content', models.TextField(blank=True, verbose_name='Contenu du code soumis')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de correction'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soumission de Projet',
                'verbose_name_plural': 'Soumissions de Projets',
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texte du choix')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est la bonne réponse')),
            ],
            options={
                'verbose_name': 'Choix de Quiz',
                'verbose_name_plural': 'Choix de Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Intitulé de la question')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication (affichée après réponse)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Question de Quiz',
                'verbose_name_plural': 'Questions de Quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Code soumis')),
                ('last_result', models.JSONField(blank=True, null=True, verbose_name="Dernier résultat d'exécution")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soumission de Code',
                'verbose_name_plural': 'Soumissions de Code',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée')),
                ('last_watched_position', models.PositiveIntegerField(default=0, verbose_name='Position vidéo (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progression Leçon',
                'verbose_name_plural': 'Progressions Leçons',
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la note')),
                ('video_timecode', models.PositiveIntegerField(default=0, verbose_name='Timecode vidéo (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['lesson', 'video_timecode'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Score obtenu (%)')),
                ('passed', models.BooleanField(verbose_name='Réussi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentative de Quiz',
                'verbose_name_plural': 'Tentatives de Quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('course_completion', 'Attestation de suivi de cours'), ('path_certification', 'Certification professionnelle')], default='course_completion', max_length=25, verbose_name='Type')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Cours (si attestation)')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.learningpath', verbose_name='Parcours (si certification)')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
    ]
