# Generated by Django 5.2.13 on 2026-05-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, verbose_name='URL du dépôt (ex: GitHub)')),
                ('code_content', models.TextField(blank=True, verbose_name='Contenu du code soumis')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de correction'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soumission de Projet',
                'verbose_name_plural': 'Soumissions de Projets',
            },
        ),
        migrations.CreateModel(
            name='ProjectPeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Note (sur 100)')),
                ('feedback', models.TextField(verbose_name='Commentaires constructifs')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Projet validé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='learning.projectsubmission')),
            ],
            options={
                'verbose_name': 'Correction par les pairs',
                'verbose_name_plural': 'Corrections par les pairs',
                'unique_together': {('reviewer', 'submission')},
            },
        ),
    ]
