# Generated by Django 5.2.14 on 2026-05-11 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('learning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathenrollment',
            options={'verbose_name': 'Inscription Parcours', 'verbose_name_plural': 'Inscriptions Parcours'},
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.learningpath'),
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pathenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
