# Generated by Django 5.2.14 on 2026-05-11 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_pathenrollment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la compétence')),
                ('icon', models.CharField(default='award', max_length=50, verbose_name='Icône Lucide')),
                ('badge_type', models.CharField(choices=[('technical', 'Compétence Technique'), ('soft_skill', 'Soft Skill / Leadership'), ('contribution', 'Contribution Communautaire')], default='technical', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='is_featured_in_portfolio',
            field=models.BooleanField(default=False, verbose_name='Afficher dans le portfolio public'),
        ),
        migrations.AddField(
            model_name='usercodesubmission',
            name='is_featured_in_portfolio',
            field=models.BooleanField(default=False, verbose_name='Afficher dans le portfolio public'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='is_featured_in_portfolio',
            field=models.BooleanField(default=False, verbose_name='Afficher dans le portfolio public'),
        ),
        migrations.AddField(
            model_name='usernote',
            name='is_featured_in_portfolio',
            field=models.BooleanField(default=False, verbose_name='Afficher dans le portfolio public'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skillbadge')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='users',
            field=models.ManyToManyField(related_name='badges', through='learning.UserBadge', through_fields=('badge', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
