# Generated by Django 5.2.14 on 2026-05-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_skillbadge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Fichier PDF'),
        ),
    ]
