# Generated by Django 5.2.14 on 2026-05-21 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_certificate_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de correction'), ('in_review', "En cours d'évaluation"), ('graded', 'Noté'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict, verbose_name='Scores par critère')),
                ('feedback', models.TextField(verbose_name='Commentaires constructifs')),
                ('review_type', models.CharField(choices=[('instructor', 'Instructeur'), ('peer', 'Pair')], default='peer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.projectsubmission')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.DeleteModel(
            name='ProjectPeerReview',
        ),
    ]
