# Generated by Django 5.2.13 on 2026-05-08 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_remove_course_prerequisites_and_more'),
        ('learning', '0005_usercodesubmission_last_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Inscription Cours', 'verbose_name_plural': 'Inscriptions Cours'},
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('course_completion', 'Attestation de suivi de cours'), ('path_certification', 'Certification professionnelle')], default='course_completion', max_length=25, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.learningpath', verbose_name='Parcours (si certification)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Cours (si attestation)'),
        ),
        migrations.CreateModel(
            name='CertificationExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Score obtenu (%)')),
                ('passed', models.BooleanField(verbose_name='Réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.certificationexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tentative d'Examen",
                'verbose_name_plural': "Tentatives d'Examen",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Progression (%)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Parcours terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Certifié')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.learningpath', verbose_name='Parcours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription Parcours',
                'verbose_name_plural': 'Inscriptions Parcours',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'learning_path')},
            },
        ),
    ]
