# Generated by Django 5.2.14 on 2026-05-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_projectsubmission_status_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigné'), ('completed', 'Terminé')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Commentaires constructifs'),
        ),
    ]
