# Generated by Django 5.2.14 on 2026-05-23 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_options_and_more'),
        ('learning', '0007_review_status_alter_review_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.learningpath', verbose_name='Parcours'),
        ),
    ]
