# Generated by Django 5.2.16 on 2026-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_certificate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Signature Cryptographique SHA-256'),
        ),
    ]
