# Generated by Django 5.2.17 on 2026-08-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_certificate_verification_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='Lien du PDF généré (externe)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('refunded', 'Remboursé'), ('free_tier', 'Accès Gratuit / Bêta')], default='pending', max_length=20, verbose_name='Statut de paiement'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion'),
        ),
    ]
