# Generated by Django 5.2.14 on 2026-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_category_alter_channel_options_channel_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
