# Generated by Django 5.2.14 on 2026-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_channelmessage_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('chat', 'Chat Classique'), ('forum', 'Espace Forum / Annonces')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre de la publication (Forum)'),
        ),
    ]
