# Generated by Django 5.2.14 on 2026-06-04 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_channel_channel_type_channelmessage_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsoredchallenge',
            options={'ordering': ['-created_at'], 'verbose_name': 'Challenge Sponsorisé', 'verbose_name_plural': 'Challenges Sponsorisés'},
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='dataset_url',
            field=models.URLField(blank=True, verbose_name='Lien vers le dataset'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='evaluation_criteria',
            field=models.TextField(blank=True, verbose_name="Critères d'évaluation"),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='has_auto_grading',
            field=models.BooleanField(default=False, verbose_name='Évaluation automatique activée'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Validé par MLAcademy'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Ouvert à tous'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Places (0 = illimité)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='private_test_dataset_url',
            field=models.URLField(blank=True, verbose_name='Dataset de test privé (auto-grading)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant du prix (FCFA)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='rules',
            field=models.TextField(blank=True, verbose_name='Règles et contraintes'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre du challenge'),
        ),
        migrations.CreateModel(
            name='DirectConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='community.joboffer', verbose_name='Offre liée (optionnel)')),
                ('participants', models.ManyToManyField(related_name='direct_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Directe',
                'verbose_name_plural': 'Conversations Directes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.directconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Direct',
                'verbose_name_plural': 'Messages Directs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True, verbose_name='Lien GitHub / dépôt')),
                ('description', models.TextField(blank=True, verbose_name='Description de la solution')),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien démo live')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Score (jury)')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Classement final')),
                ('jury_feedback', models.TextField(blank=True, verbose_name='Commentaires du jury')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('evaluated', 'Évalué'), ('winner', 'Gagnant')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='community.sponsoredchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soumission de Challenge',
                'verbose_name_plural': 'Soumissions de Challenges',
                'ordering': ['rank', '-score'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_challenge_user_submission')],
            },
        ),
    ]
