# Generated by Django 5.2.14 on 2026-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_sponsoredchallenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='position_geographique',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Montant du prix (FCFA)'),
        ),
    ]
