# Generated by Django 5.2.14 on 2026-07-26 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_company_position_geographique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengesubmission',
            options={'ordering': ['rank', '-score', '-submitted_at'], 'verbose_name': 'Soumission de Challenge', 'verbose_name_plural': 'Soumissions de Challenges'},
        ),
        migrations.AlterModelOptions(
            name='sponsoredchallenge',
            options={'ordering': ['progression_order', '-created_at'], 'verbose_name': 'Challenge Sponsorisé', 'verbose_name_plural': 'Challenges Sponsorisés'},
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='notebook_url',
            field=models.URLField(blank=True, verbose_name='Lien Notebook / Kaggle / Colab'),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='pdf_report_url',
            field=models.URLField(blank=True, verbose_name='Lien Rapport PDF'),
        ),
        migrations.AddField(
            model_name='challengesubmission',
            name='submission_number',
            field=models.PositiveIntegerField(default=1, verbose_name='N° de soumission'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='allow_teams',
            field=models.BooleanField(default=False, verbose_name='Équipes autorisées'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='badge_reward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Badge débloqué (ex: 🥇 Winner)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='category',
            field=models.CharField(choices=[('machine_learning', 'Machine Learning'), ('data_science', 'Data Science'), ('deep_learning', 'Deep Learning'), ('nlp', 'NLP / Traitement du Langage'), ('computer_vision', 'Vision par Ordinateur'), ('data_engineering', 'Data Engineering'), ('mlops', 'MLOps'), ('generative_ai', 'IA Générative'), ('quantum_ml', 'Quantum ML'), ('business_analytics', 'Business Analytics')], default='machine_learning', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='challenge_type',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('hackathon', 'Hackathon'), ('competition', 'Compétition'), ('sprint', 'Sprint'), ('bootcamp', 'Bootcamp Challenge'), ('kaggle', 'Kaggle Style')], default='competition', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='dataset_license',
            field=models.CharField(blank=True, max_length=100, verbose_name='Licence (ex: MIT, CC BY 4.0)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='dataset_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Taille du dataset (ex: 1.2 GB)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, verbose_name='Livrables attendus (ex: Notebook, Code, PDF)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='enable_public_leaderboard',
            field=models.BooleanField(default=True, verbose_name='Activer Leaderboard public'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='evaluation_mode',
            field=models.CharField(choices=[('auto', 'Évaluation Automatique'), ('jury', 'Évaluation par Jury'), ('hybrid', 'Évaluation Mixte')], default='hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='first_prize',
            field=models.CharField(blank=True, max_length=255, verbose_name='Premier prix 🥇'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='is_dataset_private',
            field=models.BooleanField(default=False, verbose_name='Dataset privé'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='max_team_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Taille max par équipe'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mentor principal'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objectif du challenge'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='organizer_website',
            field=models.URLField(blank=True, verbose_name='Site web organisateur'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='other_perks',
            field=models.TextField(blank=True, verbose_name='Avantages (Stage, Mentorat, Goodies)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='prerequisite_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_challenges', to='community.sponsoredchallenge'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='progression_order',
            field=models.IntegerField(default=0, verbose_name='Ordre dans le parcours'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='ranking_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('master', 'Master'), ('grand_master', 'Grand Master')], default='bronze', max_length=30, verbose_name='Palier de niveau'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='recommended_tech',
            field=models.JSONField(blank=True, default=list, verbose_name='Technologies (ex: Python, PyTorch, XGBoost)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='results_date',
            field=models.DateField(blank=True, null=True, verbose_name='Annonce des résultats'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='second_prize',
            field=models.CharField(blank=True, max_length=255, verbose_name='Deuxième prix 🥈'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Courte description (carte)'),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'ouverture"),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert'), ('closed', 'Fermé'), ('evaluating', 'En évaluation'), ('completed', 'Terminé')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsoredchallenge',
            name='third_prize',
            field=models.CharField(blank=True, max_length=255, verbose_name='Troisième prix 🥉'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='Lien démo live / API'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description de la solution & méthode'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Score (métrique/jury)'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('evaluated', 'Évalué'), ('winner', 'Gagnant')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='dataset_url',
            field=models.URLField(blank=True, verbose_name='Lien vers le dataset public'),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='has_auto_grading',
            field=models.BooleanField(default=False, verbose_name='Auto-grading activé'),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='private_test_dataset_url',
            field=models.URLField(blank=True, verbose_name='Dataset de test privé'),
        ),
        migrations.AlterField(
            model_name='sponsoredchallenge',
            name='reward',
            field=models.CharField(blank=True, max_length=255, verbose_name='Récompense globale'),
        ),
    ]
