# Generated by Django 5.2.16 on 2026-08-05 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_challengesubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du badge')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(verbose_name="Conditions d'obtention")),
                ('icon', models.CharField(default='trophy', help_text="Nom d'icône Lucide (ex: trophy, flame, zap, award)", max_length=100)),
                ('category', models.CharField(choices=[('learning', 'Apprentissage'), ('challenge', 'Challenges'), ('community', 'Communauté'), ('streak', 'Constance'), ('rank', 'Rangs & Tiers'), ('secret', 'Badges Secrets')], default='learning', max_length=30)),
                ('xp_reward', models.IntegerField(default=100, verbose_name='Points XP accordés')),
                ('condition_type', models.CharField(choices=[('lesson_completed', 'Leçons complétées'), ('quiz_perfect', 'Score parfait au Quiz'), ('challenge_submitted', 'Solution de Challenge soumise'), ('streak_days', "Série de jours d'apprentissage"), ('first_login', 'Première connexion'), ('night_owl', 'Abeille du soir / Nuit'), ('bug_hunter', 'Chasseur de bugs'), ('top_leaderboard', 'Top Leaderboard'), ('manual', 'Manuel / Spécial')], default='lesson_completed', max_length=50)),
                ('condition_value', models.IntegerField(default=1, help_text='Valeur nécessaire pour débloquer (ex: 5 leçons)')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Badge masqué / secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Série actuelle (jours)')),
                ('max_streak', models.IntegerField(default=0, verbose_name='Record de série (jours)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name="Dernier jour d'activité")),
                ('streak_freezes_available', models.IntegerField(default=1, verbose_name='Protections Streak Freeze disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Série d'apprentissage",
                'verbose_name_plural': "Séries d'apprentissage",
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False, help_text='Indique si la popup de félicitations a été affichée')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='community.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge Utilisateur',
                'verbose_name_plural': 'Badges Utilisateurs',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
