# Generated by Django 5.2.13 on 2026-05-05 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_url', models.URLField(blank=True, verbose_name='Lien vers le CV (LinkedIn, Drive, etc.)')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Lien vers Portfolio/GitHub')),
                ('motivation', models.TextField(verbose_name='Motivations pour devenir instructeur')),
                ('expertise_areas', models.CharField(max_length=255, verbose_name="Domaines d'expertise")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature Instructeur',
                'verbose_name_plural': 'Candidatures Instructeurs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
