# Generated by Django 5.2.14 on 2026-05-10 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorapplication',
            name='expertise_areas',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Est instructeur'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='activation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='activation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='activation_token_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='instructor_cvs/', verbose_name='Fichier CV (PDF, Word)'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='expertise',
            field=models.CharField(choices=[('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('data_science', 'Data Science'), ('nlp', 'NLP / Traitement du langage'), ('computer_vision', 'Vision par ordinateur'), ('mlops', 'MLOps / Déploiement'), ('mathematics', 'Mathématiques pour le ML'), ('python', 'Python & Data Engineering'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='expertise_detail',
            field=models.TextField(blank=True, help_text="Décris ton expertise : années d'expérience, projets, publications…"),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='teaching_experience',
            field=models.TextField(blank=True, help_text='As-tu déjà enseigné ? Formations, tutos YouTube, articles…'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instructorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
