# Generated by Django 5.2.14 on 2026-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_instructorapplication_expertise_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Site Web / Blog'),
        ),
    ]
