# Generated by Django 5.2.14 on 2026-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='Est recruteur'),
        ),
    ]
