# Generated by Django 5.2.14 on 2026-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='Est mentor'),
        ),
    ]
