# Generated by Django 5.2.14 on 2026-05-12 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_zip', models.CharField(blank=True, max_length=20)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_country', models.CharField(default='Bénin', max_length=100)),
                ('french_level', models.CharField(blank=True, max_length=50)),
                ('english_level', models.CharField(blank=True, max_length=50)),
                ('current_situation', models.CharField(blank=True, max_length=100)),
                ('professional_experiences', models.JSONField(blank=True, default=list)),
                ('work_permits', models.JSONField(blank=True, default=list)),
                ('specific_statuses', models.JSONField(blank=True, default=list)),
                ('diplomas', models.JSONField(blank=True, default=list)),
                ('hours_per_week', models.IntegerField(default=20)),
                ('desired_start_date', models.DateField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('honor_declaration_accepted', models.BooleanField(default=False)),
                ('selected_training_slug', models.SlugField(blank=True, max_length=100)),
                ('funding_method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
