# Generated by Django 5.2.14 on 2026-05-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='xp_points',
            field=models.IntegerField(default=0, verbose_name="Points d'expérience"),
        ),
    ]
