# Generated by Django 5.2.14 on 2026-06-12 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_studentprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Bannière de profil')),
                ('headline', models.CharField(blank=True, default='Machine Learning Engineer', max_length=150, verbose_name='Titre professionnel')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('github_url', models.URLField(blank=True, verbose_name='Profil GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Profil X/Twitter')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Instructeur',
                'verbose_name_plural': 'Profils Instructeurs',
            },
        ),
    ]
