# Generated by Django 5.2.14 on 2026-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_instructorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('changes_requested', 'Modifications demandées'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
