# Generated by Django 5.2.14 on 2026-06-23 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_options_and_more'),
        ('users', '0011_alter_instructorapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTesteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text="Indique si l'administrateur a validé ce profil comme bêta-testeur officiel.")),
                ('motivation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Cours disponibles pour les bêta-testeurs (vide = accès à tout)', related_name='beta_testers', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beta_testeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bêta-testeur',
                'verbose_name_plural': 'Bêta-testeurs',
                'ordering': ['-applied_at'],
            },
        ),
    ]
