# Generated by Django 5.2.14 on 2026-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_betatesteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
