# Generated by Django 5.2.14 on 2026-07-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studentprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_sent_at',
            field=models.DateTimeField(auto_now=True, verbose_name="Date d'envoi de la vérification"),
        ),
    ]
