"""
Django settings for MLBackend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import os
import firebase_admin
from firebase_admin import credentials

# Chemin vers votre fichier JSON de clé privée téléchargé


# Charger les variables d'environnement depuis le fichier .env
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l#g$%id**%kk5q-tdxw)&89jdx&gbi+#s!ny71^fd(27o82s+6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]

CSRF_TRUSTED_ORIGINS = [
    "https://mlacademie.vercel.app",
    "https://mlacademy.onrender.com",
    "http://localhost:3000",
]
if os.getenv("FRONTEND_PROD_URL"):
    CSRF_TRUSTED_ORIGINS.append(os.getenv("FRONTEND_PROD_URL"))

# Secure cookies in production
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Strict Security Headers in Production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Force HTTPS only if specified (useful if proxy like Vercel/Nginx handles it)
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "phonenumber_field",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "rest_framework",
    "drf_spectacular",
    'rest_framework_simplejwt',
    "django_filters",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "django_otp",
    "django_otp.plugins.otp_totp",
    # Local apps
    "users",
    "courses",
    "learning",
    "management",
    "community",
    "notifications",
    "chat",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

]

ROOT_URLCONF = "MLBackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MLBackend.wsgi.application"
ASGI_APPLICATION = "MLBackend.asgi.application"

if os.getenv("REDIS_URL"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.getenv("REDIS_URL")],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "AcademyDB",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # "NAME": "postgres",
    }
}

if os.getenv("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True,
    )

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'asyncio': {
            'handlers': ['console'],
            'level': 'WARNING',  # Évite d'afficher les infos ou erreurs mineures d'annulation
        },
    },
}
JAZZMIN_SETTINGS = {
    # --- Titres et Branding ---
    "site_title": "MLAcademy Admin",
    "site_header": "MLAcademy",
    "site_brand": "MLAcademy",
    # "site_logo": "images/logo_mlacademy.png", 
    "login_logo": None,
    "welcome_sign": "Bienvenue sur la plateforme d'administration de MLAcademy",
    "copyright": "MLAcademy. All rights reserved.",

    # --- Ergonomie et Navigation ---
    "search_model": ["users.CustomUser"], # Permet une barre de recherche globale (ex: chercher un utilisateur)
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    
    # Personnalisation des Icônes (FontAwesome)
    "icons": {
        "users.CustomUser": "fas fa-users-cog",
        "users.CustomUser": "fas fa-user",
        "users.CustomGroup": "fas fa-users",

    },
    # Icônes par défaut pour les applications et modèles si non spécifiés
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # --- Liens et Raccourcis Rapides ---
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["users.view_customuser"]},
        {"name": "Voir le site", "url": "/", "new_window": True},
        # model admin to link to (Permissions checked against model)
        {"model": "users.CustomUser"},
        {"app": "users"},
    ],
    
    # Menu Utilisateur 
    "usermenu_links": [
        {"name": "Support MLAcademy", "url": "https://mlacademy.com", "new_window": True},
    ],

    "language_chooser": True,
    "changeform_format_overrides": {"users.CustomUser": "collapsible", "users.CustomGroup": "vertical_tabs"},

    # Style et Thème
    "theme": "dark",  # Votre choix initial
    # "dark_mode_theme": "darkly", # Vous pouvez tester d'autres variantes de thèmes sombres Boootstrap (ex: slate, cyborg, darkly)
    
    # Options d'interface
    "show_ui_builder": False, # Mettez True pendant le développement pour tester les couleurs en direct, puis False en production
    "changeform_format": "horizontal_tabs", # Organise les formulaires d'édition longs en onglets (très propre !)
}

JAZZMIN_UI_TWEAKS = {
    "theme": "slate",
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Porto-Novo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "MLBackend.storage.IgnoreMissingManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Modèle utilisateur personnalisé
AUTH_USER_MODEL = "users.CustomUser"

# Django Rest Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/day",
        "user": "20/hour",
        "login": "5/minute",
        "ai_chat": "100/day",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,

    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",

    # Indique à DRF d'utiliser drf-spectacular pour le schéma
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
# Configuration optionnelle pour personnaliser la doc
SPECTACULAR_SETTINGS = {
    'TITLE': 'MLAcademy API',
    'DESCRIPTION': 'Documentation automatique de mon application',
    'VERSION': '1.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Optionnel : pour trier les opérations par tags
    'COMPONENT_SPLIT_REQUEST': True, 
}
# JWT Configuration (djangorestframework-simplejwt)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
}

# CORS Configuration for development
CORS_ALLOW_CREDENTIALS = True
cors_allowed_origins_env = os.getenv("CORS_ALLOWED_ORIGINS", "https://mlacademie.vercel.app,https://mlacademy.onrender.com,http://localhost:3000")
CORS_ALLOWED_ORIGINS = [orig.strip() for orig in cors_allowed_origins_env.split(",") if orig.strip()]
CORS_ALLOW_HEADERS = list(
    (
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
    )
)

# Email Configuration (SMTP par défaut car pas de nom de domaine pour Resend)
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# Configuration Resend (Prêt pour quand vous aurez un domaine)
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
DEFAULT_FROM_EMAIL = "noreply@mlacademy.io"

# Celery Configuration
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# django-allauth Configuration
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"  # Géré manuellement via notre vue
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = "https://mlacademie.vercel.app/onboarding"
LOGOUT_REDIRECT_URL = "https://mlacademie.vercel.app/login"
FRONTEND_URL = "https://mlacademie.vercel.app"

# Configuration des providers OAuth (évite de stocker les clés dans la DB)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID", ""),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["user", "user:email"],
    },
}

# Durée de validité du token de réinitialisation (en secondes)
PASSWORD_RESET_TIMEOUT = 3600  # 1 heure

# Hashage des mots de passe (bcrypt en priorité)
AUTH_PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # fallback
]

# Media files (avatars, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Sandbox Configuration pour l'exécution de code
SANDBOX_URL = os.getenv("SANDBOX_URL", "http://localhost:8000/execute")

cred_path = os.path.join(os.path.dirname(__file__), 'mlacademy-82d8b-firebase-adminsdk-fbsvc-9d6ae399a8.json')

if os.path.exists(cred_path):
    cred = credentials.Certificate(cred_path)
    firebase_admin.initialize_app(cred)
    print("Firebase Admin initialisé avec succès !")