name: CI
on:
  push:
    branches: [develop, courses]
  pull_request:
    branches: [develop, courses]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.21.1'
          cache: 'npm'
          cache-dependency-path: AcademyFrontend/package-lock.json
      - name: Install & Lint
        run: |
          cd AcademyFrontend
          npm install
          npm run lint
      - name: Type Check
        run: |
          cd AcademyFrontend
          npx tsc --noEmit

  backend:
    name: Backend MLAcademy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'
      - name: Install dependencies
        run: |
          cd MLBackend
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd MLBackend
          python manage.py test

  sandbox:
    name: Sandbox (FastAPI) CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'
      - name: Install dependencies
        run: |
          cd MLSandbox
          pip install -r requirements.txt
      - name: Run Lint
        run: |
          pip install flake8
          flake8 MLSandbox/main.py
